GET http://localhost:3002/modsearch/CS1010S

###

POST http://localhost:3002/login
Content-Type: application/json

{
    "username": "bob",
    "password": "123456"
}

###

POST http://localhost:3002/token/
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQm9iIiwiaWF0IjoxNjU3OTczNDA3fQ.sG1j_fcBVT8WLwiR1yIxmC-16leII0lvkd7sCYogq78" 
}

###
DELETE  http://localhost:3002/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQm9iIiwiaWF0IjoxNjU3OTczNDA3fQ.sG1j_fcBVT8WLwiR1yIxmC-16leII0lvkd7sCYogq78"
}

###
POST http://localhost:3002/signup
Content-Type: application/json

{
    "firstName": "Hello",
    "lastName": "World",
    "username": "bob",
    "password": "123456",
    "course": "Information Systems"
}